---
save_local: "{{global.save_local|default('enabled')}}"

bird_folder_local: "config/{{ansible_hostname}}/etc"
bird4_conf_local: "{{bird_folder_local}}/bird4.conf"
bird6_conf_local: "{{bird_folder_local}}/bird6.conf"
bird4_conf_alt: "/etc/bird/bird4.conf"
bird6_conf_alt: "/etc/bird/bird6.conf"
bird4_conf_debian: "/etc/bird.conf"
bird4_conf_redhat: "/etc/bird.conf"

bird_logfile: "/var/log/bird.log"
bird_debug: "states, routes, filters, interfaces, events"
